### ISSUE TITLE
【求助】显示模式下，点击带有监听事件的TextView崩溃，无法打开 带有ViewInfo的PopupWindow

### ISSUE THREAD

**Issue by Floyd-pro** [niuxiaowei/LayoutInspector#1]
【求助】显示模式下，点击带有监听事件的TextView崩溃，无法打开 带有ViewInfo的PopupWindow

最低Sdk版本：21 (24、27都试了同样报错)
手机机型：HUAWEI mate 30

项目根目录gradle和app的gradle配置如下
![Snipaste_2022-03-01_14-38-04](https://user-images.githubusercontent.com/78715483/156118021-90c11f97-221a-47d9-b2fb-9167c2db882c.png)
（其余跟教程配置的一样，就不截图了）
![Snipaste_2022-03-01_14-39-10](https://user-images.githubusercontent.com/78715483/156118035-5a5fc0d0-7e7d-4ff3-b980-e42efac4aeef.png)

崩溃堆栈信息如下
AndroidRuntime: FATAL EXCEPTION: main
java.lang.NoSuchMethodError: No virtual method hasOnLongClickListeners()Z in class Landroid/view/View; or its super classes (declaration of 'android.view.View' appears in /system/framework/framework.jar!classes3.dex)
        at com.mi.layoutinspector.viewinfos.viewattributes.ViewClickInfoCollector.collectViewAttributes(ViewClickInfoCollector.kt:28)
        at com.mi.layoutinspector.viewinfos.ViewInfosPopupWindow.collectViewAttributes(ViewInfosPopupWindow.kt:166)
        at com.mi.layoutinspector.viewinfos.ViewInfosPopupWindow.showViewInfos(ViewInfosPopupWindow.kt:132)
        at com.mi.layoutinspector.inspector.PageInspector.showViewInfosPopupWindow(PageInspector.kt:180)
        at com.mi.layoutinspector.inspector.ViewInspector.showViewInfosPopupWindow(ViewInspector.kt:94)
        at com.mi.layoutinspector.inspector.ViewInspector$1.onClick(ViewInspector.kt:71)
        at com.mi.layoutinspector.replacemethod.OnClickListenerProxy$ClickListenerWrapper.onClick(OnClickListenerProxy.java:35)
        at android.view.View.performClick(View.java:7312)
        at android.view.View.performClickInternal(View.java:7286)
        at android.view.View.access$3600(View.java:838)
        at android.view.View$PerformClick.run(View.java:28242)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by niuxiaowei** [comment]
@Floyd-pro 已解决，使用  2.0.2 版本
